--DDL Script: 
CREATE TABLE student_coll_dv_course(
   appl_info  varchar2(64),
   course_id  number  GENERATED BY DEFAULT ON NULL AS IDENTITY,
   addtl_info  varchar2(64),
   course_desc  varchar2(1024)  /* UNIQUE */,
   course_name  varchar2(64)  /* UNIQUE */,
   ora$student_coll_dv_flex  JSON(Object),
   PRIMARY KEY(course_id)
);

CREATE TABLE student_coll_dv_attended_course(
   studentschedulestuid  varchar2(64),
   studentscheduleroomid  varchar2(64)  /* UNIQUE */,
   studentscheduleschedid  number  /* UNIQUE */,
   studentscheduleteachid  varchar2(64)  DEFAULT ON NULL SYS_GUID(),
   stuid_student_coll_dv_root  varchar2(64),
   course_id_student_coll_dv_course  number,
   room_building_student_coll_dv_room  varchar2(64),
   teacher_number_student_coll_dv_teacher  number,
   ora$student_coll_dv_flex  JSON(Object),
   PRIMARY KEY(studentscheduleteachid)
);

CREATE TABLE student_coll_dv_room(
   room_id  varchar2(64)  /* UNIQUE */,
   room_name  varchar2(64)  /* UNIQUE */,
   room_building  varchar2(64)  DEFAULT ON NULL SYS_GUID(),
   room_facility  json VALIDATE CAST USING '{"oneOf" : [{ "type" :"null"}, { "type" :"array"}]}',
   extra_forniture  json VALIDATE CAST USING '{"oneOf" : [{ "type" :"null"}, { "type" :"array"}]}',
   extra_ergonomics  json VALIDATE CAST USING '{"oneOf" : [{ "type" :"null"}, { "type" :"array"}]}',
   room_description  varchar2(64)  /* UNIQUE */,
   building_facility  json VALIDATE CAST USING '{"oneOf" : [{ "type" :"null"}, { "type" :"array"}]}',
   extra_technology_integration  json VALIDATE CAST USING '{"oneOf" : [{ "type" :"null"}, { "type" :"array"}]}',
   ora$student_coll_dv_flex  JSON(Object),
   PRIMARY KEY(room_building)
);

CREATE TABLE student_coll_dv_root(
   stuid  varchar2(64)  DEFAULT ON NULL SYS_GUID(),
   gender  varchar2(64)  /* UNIQUE */,
   address  varchar2(64)  /* UNIQUE */,
   last_name  varchar2(64)  /* UNIQUE */,
   birth_date  timestamp,
   first_name  varchar2(64)  /* UNIQUE */,
   expectation  varchar2(128)  /* UNIQUE */,
   learning_style  json VALIDATE CAST USING '{"oneOf" : [{ "type" :"null"}, { "type" :"array"}]}',
   language_spoken  varchar2(64)  /* UNIQUE */,
   computer_literacy  varchar2(64)  /* UNIQUE */,
   educational_level  varchar2(64)  /* UNIQUE */,
   location_latitude  number  /* UNIQUE */,
   use_of_technology  json VALIDATE CAST USING '{"oneOf" : [{ "type" :"null"}, { "type" :"array"}]}',
   language_preferred  varchar2(64)  /* UNIQUE */,
   location_longitude  number  /* UNIQUE */,
   ora$student_coll_dv_flex  JSON(Object),
   PRIMARY KEY(stuid)
);

CREATE TABLE student_coll_dv_teacher(
   teacher_id  varchar2(64)  /* UNIQUE */,
   teacher_gender  varchar2(64),
   teacher_number  number  GENERATED BY DEFAULT ON NULL AS IDENTITY,
   differentiation  varchar2(256),
   lesson_planning  varchar2(256),
   teacher_address  varchar2(64)  /* UNIQUE */,
   active_listening  varchar2(256),
   ethical_attitude  json VALIDATE CAST USING '{"oneOf" : [{ "type" :"null"}, { "type" :"array"}]}',
   support_attitude  json VALIDATE CAST USING '{"oneOf" : [{ "type" :"null"}, { "type" :"array"}]}',
   teacher_last_name  varchar2(64)  /* UNIQUE */,
   teacher_birth_date  timestamp,
   teacher_first_name  varchar2(64)  /* UNIQUE */,
   professional_attitude  json VALIDATE CAST USING '{"oneOf" : [{ "type" :"null"}, { "type" :"array"}]}',
   questioning_techniques  varchar2(256),
   teacher_language_spoken  varchar2(64)  /* UNIQUE */,
   teacher_office_latitude  number  /* UNIQUE */,
   teacher_office_longitude  number  /* UNIQUE */,
   teacher_language_preferred  varchar2(64)  /* UNIQUE */,
   ora$student_coll_dv_flex  JSON(Object),
   PRIMARY KEY(teacher_number)
);

ALTER TABLE student_coll_dv_attended_course
ADD CONSTRAINT fk_student_coll_dv_attended_course_to_student_coll_dv_room FOREIGN KEY (room_building_student_coll_dv_room) REFERENCES student_coll_dv_room(room_building) DEFERRABLE;
ALTER TABLE student_coll_dv_attended_course
ADD CONSTRAINT fk_student_coll_dv_attended_course_to_student_coll_dv_root FOREIGN KEY (stuid_student_coll_dv_root) REFERENCES student_coll_dv_root(stuid) DEFERRABLE;
ALTER TABLE student_coll_dv_attended_course
ADD CONSTRAINT fk_student_coll_dv_attended_course_to_student_coll_dv_course FOREIGN KEY (course_id_student_coll_dv_course) REFERENCES student_coll_dv_course(course_id) DEFERRABLE;
ALTER TABLE student_coll_dv_attended_course
ADD CONSTRAINT fk_student_coll_dv_attended_course_to_student_coll_dv_teacher FOREIGN KEY (teacher_number_student_coll_dv_teacher) REFERENCES student_coll_dv_teacher(teacher_number) DEFERRABLE;
CREATE INDEX IF NOT EXISTS fk_student_coll_dv_attended_course_to_student_coll_dv_room_index ON student_coll_dv_attended_course(room_building_student_coll_dv_room);
CREATE INDEX IF NOT EXISTS fk_student_coll_dv_attended_course_to_student_coll_dv_root_index ON student_coll_dv_attended_course(stuid_student_coll_dv_root);
CREATE INDEX IF NOT EXISTS fk_student_coll_dv_attended_course_to_student_coll_dv_course_index ON student_coll_dv_attended_course(course_id_student_coll_dv_course);
CREATE INDEX IF NOT EXISTS fk_student_coll_dv_attended_course_to_student_coll_dv_teacher_index ON student_coll_dv_attended_course(teacher_number_student_coll_dv_teacher);

CREATE OR REPLACE JSON RELATIONAL DUALITY VIEW STUDENT_COLL_DV AS 
student_coll_dv_root @insert @update @delete
{ 
  _id : stuid
  stuid @generated (path: "$._id")
  gender
  address
  last_name
  birth_date
  first_name
  expectation
  LEARNING_STYLE: learning_style
  attended_course: student_coll_dv_attended_course @insert @update @delete @array
  [{ 
    room: student_coll_dv_room @insert @update @object
    { 
      room_id
      room_name
      ROOM_FACILITY: room_facility
      room_building
      extra_forniture
      extra_ergonomics
      room_description
      BUILDING_FACILITY: building_facility
      extra_technology_integration
      ora$student_coll_dv_flex @flex
    } 
    course: student_coll_dv_course @insert @update @object
    { 
      appl_info
      course_id
      addtl_info
      course_desc
      course_name
      ora$student_coll_dv_flex @flex
    } 
    teacher: student_coll_dv_teacher @insert @update @object
    { 
      teacher_id
      teacher_gender
      teacher_number
      Differentiation: differentiation
      Lesson_Planning: lesson_planning
      teacher_address
      Active_Listening: active_listening
      ETHICAL_ATTITUDE: ethical_attitude
      SUPPORT_ATTITUDE: support_attitude
      teacher_last_name
      teacher_birth_date
      teacher_first_name
      PROFESSIONAL_ATTITUDE: professional_attitude
      Questioning_Techniques: questioning_techniques
      teacher_language_spoken
      teacher_office_latitude
      teacher_office_longitude
      teacher_language_preferred
      ora$student_coll_dv_flex @flex
    } 
    studentschedulestuid
    studentscheduleroomid
    studentscheduleschedid
    studentscheduleteachid
    ora$student_coll_dv_flex @flex
  }] 
  language_spoken
  USE_OF_TECHNOLOGY: use_of_technology
  computer_literacy
  educational_level
  location_latitude
  language_preferred
  location_longitude
  ora$student_coll_dv_flex @flex
}; 

CREATE OR REPLACE TRIGGER INSERT_TRIGGER_STUDENT_COLL_DV
  BEFORE INSERT
  ON STUDENT_COLL_DV
  FOR EACH ROW
DECLARE 
  inp_jsonobj json_object_t;
BEGIN
  inp_jsonobj := json_object_t(:new.data);
  IF NOT inp_jsonobj.has('_id') 
  THEN 
    inp_jsonobj.put('_id', inp_jsonobj.get('stuid'));
    :new.data := inp_jsonobj.to_json;
  END IF;
END; 
/
-- PL/SQL procedure successfully completed.

